export const apiTableData = [
  {
    application_name: 'CUSTOMER_ACCOUNT_GATEWAY',
    name: 'GET_DEMOGRAPHICS_API.ENABLED',
    group: 'API_CONTROL',
    value: 'TRUE',
    description: 'Switch enabling/disabling Get Demographics API',
    version: 78,
    last_updated: {
      source: 'SUPPORT-UI',
      user_id: 'sthoppil',
    },
  },
  {
    application_name: 'CUSTOMER_ACCOUNT_GATEWAY',
    name: 'GET_DEMOGRAPHICS_API.STUB.ENABLED',
    group: 'API_CONTROL',
    value: 'TRUE',
    description: 'Switch enabling/disabling Get Demographics API Stub',
    version: 24,
    last_updated: {
      source: 'SUPPORT-UI',
      user_id: 'sthoppil',
    },
  },
  {
    application_name: 'CUSTOMER_ACCOUNT_GATEWAY',
    name: 'GET_LINKED_CUSTOMER_ACCOUNTS_V2_API.ENABLED',
    group: 'API_CONTROL',
    value: 'TRUE',
    description: 'Switch enabling/disabling Get Linked customer accounts API V2',
    version: 19,
    last_updated: {
      source: 'SUPPORT-UI',
      user_id: 'sthoppil',
    },
  },
  {
    application_name: 'CUSTOMER_ACCOUNT_GATEWAY',
    name: 'GET_LINKED_CUSTOMER_ACCOUNTS_V2_API.STUB.ENABLED',
    group: 'API_CONTROL',
    value: 'TRUE',
    description: 'Switch enabling/disabling Get Linked customer accounts API V2 Stub',
    version: 19,
    last_updated: {
      source: 'SUPPORT-UI',
      user_id: 'sthoppil',
    },
  },
  {
    application_name: 'CUSTOMER_ACCOUNT_GATEWAY',
    name: 'GET_DEMOGRAPHICS_V2_API.STUB.ENABLED',
    group: 'API_CONTROL',
    value: 'TRUE',
    description: 'Switch enabling/disabling Get Demographics API V2 Stub',
    version: 20,
    last_updated: {
      source: 'SUPPORT-UI',
      user_id: 'ideskov',
    },
  },
  {
    application_name: 'CUSTOMER_ACCOUNT_GATEWAY',
    name: 'UPDATE_DEMOGRAPHICS_API.STUB.ENABLED',
    group: 'API_CONTROL',
    value: 'TRUE',
    description: 'Switch enabling/disabling Update Demographics API Stub',
    version: 16,
    last_updated: {
      source: 'SUPPORT-UI',
      user_id: 'ideskov',
    },
  },
  {
    application_name: 'CUSTOMER_ACCOUNT_GATEWAY',
    name: 'UPDATE_DEMOGRAPHICS_API.ENABLED',
    group: 'API_CONTROL',
    value: 'TRUE',
    description: 'Switch providing control for Update Demographics API processing',
    version: 1,
    last_updated: {
      source: 'SUPPORT-UI',
      user_id: 'sthoppi',
    },
  },
  {
    application_name: 'CUSTOMER_ACCOUNT_GATEWAY',
    name: 'GET_DEMOGRAPHICS_V2_API.ENABLED',
    group: 'API_CONTROL',
    value: 'TRUE',
    description: 'Switch enabling/disabling Get Demographics API V2',
    version: 4,
    last_updated: {
      source: 'SUPPORT-UI',
      user_id: 'sthoppil',
    },
  },
  {
    application_name: 'CUSTOMER_ACCOUNT_GATEWAY',
    name: 'GET_DEMOGRAPHICS_API.ENABLED',
    group: 'API_CONTROL',
    value: 'TRUE',
    description: 'Switch enabling/disabling Get Demographics API',
    version: 78,
    last_updated: {
      source: 'SUPPORT-UI',
      user_id: 'sthoppil',
    },
  },
  {
    application_name: 'CUSTOMER_ACCOUNT_GATEWAY',
    name: 'GET_DEMOGRAPHICS_API.STUB.ENABLED',
    group: 'API_CONTROL',
    value: 'TRUE',
    description: 'Switch enabling/disabling Get Demographics API Stub',
    version: 24,
    last_updated: {
      source: 'SUPPORT-UI',
      user_id: 'sthoppil',
    },
  },
  {
    application_name: 'CUSTOMER_ACCOUNT_GATEWAY',
    name: 'GET_LINKED_CUSTOMER_ACCOUNTS_V2_API.ENABLED',
    group: 'API_CONTROL',
    value: 'TRUE',
    description: 'Switch enabling/disabling Get Linked customer accounts API V2',
    version: 19,
    last_updated: {
      source: 'SUPPORT-UI',
      user_id: 'sthoppil',
    },
  },
  {
    application_name: 'CUSTOMER_ACCOUNT_GATEWAY',
    name: 'GET_LINKED_CUSTOMER_ACCOUNTS_V2_API.STUB.ENABLED',
    group: 'API_CONTROL',
    value: 'TRUE',
    description: 'Switch enabling/disabling Get Linked customer accounts API V2 Stub',
    version: 19,
    last_updated: {
      source: 'SUPPORT-UI',
      user_id: 'sthoppil',
    },
  },
  {
    application_name: 'CUSTOMER_ACCOUNT_GATEWAY',
    name: 'GET_DEMOGRAPHICS_V2_API.STUB.ENABLED',
    group: 'API_CONTROL',
    value: 'TRUE',
    description: 'Switch enabling/disabling Get Demographics API V2 Stub',
    version: 20,
    last_updated: {
      source: 'SUPPORT-UI',
      user_id: 'ideskov',
    },
  },
  {
    application_name: 'CUSTOMER_ACCOUNT_GATEWAY',
    name: 'UPDATE_DEMOGRAPHICS_API.STUB.ENABLED',
    group: 'API_CONTROL',
    value: 'TRUE',
    description: 'Switch enabling/disabling Update Demographics API Stub',
    version: 16,
    last_updated: {
      source: 'SUPPORT-UI',
      user_id: 'ideskov',
    },
  },
  {
    application_name: 'CUSTOMER_ACCOUNT_GATEWAY',
    name: 'UPDATE_DEMOGRAPHICS_API.ENABLED',
    group: 'API_CONTROL',
    value: 'TRUE',
    description: 'Switch providing control for Update Demographics API processing',
    version: 1,
    last_updated: {
      source: 'SUPPORT-UI',
      user_id: 'sthoppi',
    },
  },
  {
    application_name: 'CUSTOMER_ACCOUNT_GATEWAY',
    name: 'GET_DEMOGRAPHICS_V2_API.ENABLED',
    group: 'API_CONTROL',
    value: 'TRUE',
    description: 'Switch enabling/disabling Get Demographics API V2',
    version: 4,
    last_updated: {
      source: 'SUPPORT-UI',
      user_id: 'sthoppil',
    },
  },
];
