configMap:
  HOLOCRON_MODULE_MAP_URL: https://cdaas-dev.aexp.com/cdaas/one-app/map/epaas-kyc-refresh-intra-kyc-refresh-e1/module-map.json
  HTTP_METRICS_PORT: '3005'
  NODE_ENV: production
  NODE_EXTRA_CA_CERTS: /opt/amex/AmexOnDemandRootCAs.pem
  NODE_OPTIONS: --max-http-header-size=32768
  ONE_CLIENT_CDN_URL: https://cdaas-dev.aexp.com/cdaas/one/
  ONE_CLIENT_CSP_REPORTING_URL: https://kycrefreshupliftgtm-dev.aexp.com/_/report/security/csp-violation
  ONE_CLIENT_LOCALE_FILENAME: integration
  ONE_CLIENT_REPORTING_URL: https://kycrefreshupliftgtm-dev.aexp.com/_/report/errors
  ONE_CLIENT_ROOT_MODULE_NAME: know-your-customer-refresh-root
  ONE_CONFIG_ENV: e1
  OPENSHIFT_NODEJS_IP: 0.0.0.0
  HTTP_PORT: 8080
hpa:
  cpuUtilizationPercentage: 75
  enabled: true
  maxReplicas: 2
  minReplicas: 1
deployment:
  containerPort: 8080
  readinessProbe:
    httpGet:
      path: /_/status
      port: 8080
      scheme: HTTP
    initialDelaySeconds: 30
    timeoutSeconds: 15
    periodSeconds: 10
    successThreshold: 1
    failureThreshold: 3
  livenessProbe:
    httpGet:
      path: /_/status
      port: 8080
      scheme: HTTP
    initialDelaySeconds: 30
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 15
    failureThreshold: 3
  resourcesLimitsCPU: 1
  resourcesLimitsMemory: 4G
  resourcesRequestsCPU: 250m
  resourcesRequestsMemory: 1.5G
  readOnlyRootFileSystem: true
  privileged: false
  scratchvolume:
    - mountName: tmp-mount
      mountPath: /tmp
  securityContext:
    allowPrivilegeEscalation: false
    privileged: false
    readOnlyRootFilesystem: true
  volumeMounts:
    - mountPath: /tmp
      name: tmp-mount
monitoring:
  type: prometheus
  path: /metrics
  port: 3005
  enabled: true
  filter:
    mode: include
    names:
    - /_/status
    - jvm_buffer*
    - process_*
    - jvm_threads_live_threads
    - oneapp_*
    - node_*
    - nodejs_*
    - http_*
