name: Blue/Green Switch One App Server
run-name: Blue/Green Switch ${{ github.event.inputs.project }}/${{ github.event.inputs.project }} ${{ github.event.inputs.amex_environment }}

on:
  workflow_dispatch:
    inputs:
      project:
        description: The PaaS project
        required: true
        type: string
        default: 'maestro'
      service:
        description: The PaaS service
        required: true
        type: string
        default: 'rui'
      amex_environment:
        description: 'Amex environment to do the switch. Either "e2" or "e3"'
        required: true
        type: choice
        default: 'e2'
        options:
          - 'e2'
          - 'e3'

jobs:
  blue-green-switch:
    name: One App Blue/Green Switch
    uses: amex-eng/one-app-actions/.github/workflows/one-app_blue-green-switch.yaml@v1
    with:
      paas_project: ${{ github.event.inputs.project }}
      paas_service: ${{ github.event.inputs.service }}
      amex_environment: ${{ github.event.inputs.amex_environment }}
    secrets: inherit
