name: Deploy One App Server
run-name: Deploy OneApp ${{ inputs.one_app_version }} to ${{ inputs.project }}/${{ inputs.service }} ${{ inputs.amex_environment }}

on:
  workflow_dispatch:
    inputs:
      project:
        description: The PaaS project
        required: true
        type: choice
        default: 'kyc-refresh-intra'
        options:
          - 'kyc-refresh-intra'
          - 'maestro'
      service:
        description: The PaaS service
        required: true
        type: choice
        default: 'kyc-refresh'
        options:
          - 'kyc-refresh'
          - 'rui'
      amex_environment:
        description: 'Amex environment (E1, E2, E3)'
        required: true
        default: E1
        type: choice
        options:
          - E1
          - E2
          - E3
      one_app_version:
        description: Version of the one-app runtime in the form of the image label (see https://hub.docker.com/r/oneamex/one-app/tags)
        required: true
        type: string
      change_record:
        description: 'For operations requiring a change record (i.e. deploying to E3) enter the RFC Number'
        required: false
      slack_channel_id:
        description: 'Optional message to a channel of your choosing. Needs to be the alphanumeric channel ID, not the channel name.'
        required: false

jobs:
  deploy:
    name: One App to PaaS
    uses: amex-eng/one-app-actions/.github/workflows/one-app_deploy-or-promote.yml@v1
    with:
      paas_project: ${{ github.event.inputs.project }}
      paas_service: ${{ github.event.inputs.service }}
      amex_environment: ${{ github.event.inputs.amex_environment }}
      one_app_version: ${{ github.event.inputs.one_app_version }}
      change_record: ${{ github.event.inputs.change_record }}
      slack_channel_id: 'null' 
    secrets: inherit
